# Generated by Django 6.1 on 2026-08-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_city_order_email_order_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Fulfilled', 'Fulfilled'), ('Shipped', 'Shipped'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
