# Generated by Django 6.1 on 2026-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('gradient_start', models.CharField(default='#f1cdd2', max_length=7)),
                ('gradient_end', models.CharField(default='#7a2b3f', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(max_length=120)),
                ('image_key', models.CharField(default='box', help_text="Icon key used by the frontend's ProductVisual component.", max_length=40)),
                ('gradient_start', models.CharField(default='#f1cdd2', max_length=7)),
                ('gradient_end', models.CharField(default='#7a2b3f', max_length=7)),
                ('badge', models.CharField(blank=True, choices=[('', 'None'), ('Sale', 'Sale'), ('New', 'New'), ('Bestseller', 'Bestseller'), ('Sold out', 'Sold out')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='products', to='catalog.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
