# Generated by Django 6.1 on 2026-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_key',
            field=models.CharField(default='box', help_text="Icon key used by the frontend's ProductVisual component as a fallback.", max_length=40),
        ),
    ]
